"""Adiciona campo comite ao modelo Evento

Revision ID: 02cdbbebb3af
Revises: 2c5bd440a641
Create Date: 2025-05-13 20:06:53.651842

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02cdbbebb3af'
down_revision = '2c5bd440a641'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('evento', schema=None) as batch_op:
        batch_op.add_column(sa.Column('comite', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('evento', schema=None) as batch_op:
        batch_op.drop_column('comite')

    # ### end Alembic commands ###
